#ddev-generated
# If you remove the ddev-generated line above you
# are responsible for maintaining this file. DDEV will not then
# update it, for example if you add `additional_hostnames`, etc.

http:
  routers:
    secure-db-dump-web-80-http:
      entrypoints:
        - http-80
      rule: HostRegexp(`^secure-db-dump\.ddev\.site$`)

      service: "secure-db-dump-web-80"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "secure-db-dump-redirectHttps"
    secure-db-dump-web-8025-http:
      entrypoints:
        - http-8025
      rule: HostRegexp(`^secure-db-dump\.ddev\.site$`)

      service: "secure-db-dump-web-8025"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "secure-db-dump-redirectHttps"
    secure-db-dump-xhgui-80-http:
      entrypoints:
        - http-8143
      rule: HostRegexp(`^secure-db-dump\.ddev\.site$`)

      service: "secure-db-dump-xhgui-80"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "secure-db-dump-redirectHttps"



    secure-db-dump-web-80-https:
      entrypoints:
        - http-443
      rule: HostRegexp(`^secure-db-dump\.ddev\.site$`)

      service: "secure-db-dump-web-80"
      ruleSyntax: v3

      tls: true

    secure-db-dump-web-8025-https:
      entrypoints:
        - http-8026
      rule: HostRegexp(`^secure-db-dump\.ddev\.site$`)

      service: "secure-db-dump-web-8025"
      ruleSyntax: v3

      tls: true


    secure-db-dump-xhgui-80-https:
      entrypoints:
        - http-8142
      rule: HostRegexp(`^secure-db-dump\.ddev\.site$`)

      service: "secure-db-dump-xhgui-80"
      ruleSyntax: v3

      tls: true



  middlewares:
    secure-db-dump-redirectHttps:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    secure-db-dump-web-80:
      loadbalancer:
        servers:
          - url: http://ddev-secure-db-dump-web:80

    secure-db-dump-web-8025:
      loadbalancer:
        servers:
          - url: http://ddev-secure-db-dump-web:8025



    secure-db-dump-xhgui-80:
      loadbalancer:
        servers:
          - url: http://ddev-secure-db-dump-xhgui:80




tls:
  certificates:
    - certFile: /mnt/ddev-global-cache/traefik/certs/secure-db-dump.crt
      keyFile: /mnt/ddev-global-cache/traefik/certs/secure-db-dump.key
